server:

  rootPath: /customer/*
  adminConnectors:
    -
      port: 5559
      type: http
  applicationConnectors:
     -
      acceptorThreads: 4
      port: 5558
      selectorThreads: 14
      type: http
  maxQueuedRequests: 200
  maxThreads: 100
swagger:
  resourcePackage: com.target

logging:
  appenders:
    -
      type: console
      logFormat: "%-5p [%d{ISO8601}] [%X{reqId} %X{txnId}] %c: %m\n%ex"
      threshold: ALL

  level: DEBUG
  loggers:
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG